import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Navigation from "@/components/Navigation/NavigationBar";
import { getCategory } from "@/api/fetchCategory";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const data = await getCategory();
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <Navigation data={data} />
                {children}
                <Footer data={data} />
            </body>
        </html>
    );
}
